### ISSUE TITLE
python version and script spacing

### ISSUE THREAD

**Issue by jordrow** [LeopoldC/Boost-HiC#2]
The README says that it uses python2.7, but the scripts seem to actually be written for python3. Additionally, I found some lines in HiCutils.py have tab indentation while others have space indentation. This caused it to break with some python implementations.

**Comment by LeopoldC** [comment]
thanks, i will update the code.
Best
L&eacute;opold

----- Mail d'origine -----De: jordrow <notifications@github.com>&Agrave;: LeopoldC/Boost-HiC <Boost-HiC@noreply.github.com>Cc: Subscribed <subscribed@noreply.github.com>Envoy&eacute;: Mon, 20 Apr 2020 17:01:16 +0200 (CEST)Objet: [LeopoldC/Boost-HiC] python version and script spacing (#2)


The README says that it uses python2.7, but the scripts seem to actually be written for python3. Additionally, I found some lines in HiCutils.py have tab indentation while others have space indentation. This caused it to break with some python implementations.
&mdash;You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.


-- 
L&eacute;opold Carron
